# Generated by Django 5.1.2 on 2025-01-18 06:16

import django.db.models.deletion
import main.models.renovation
import main.models.stage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('default', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renovation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(default=main.models.renovation.generate_random_string, editable=False, max_length=16, verbose_name='Track')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'Renovation',
                'verbose_name_plural': 'Renovations',
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('firstname', models.CharField(max_length=255, verbose_name='Name')),
                ('lastname', models.CharField(max_length=255, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last Login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Supervisor',
                'verbose_name_plural': 'Supervisors',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renovation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='main.renovation', verbose_name='Renovation')),
                ('service_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='default.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_ka', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('is_completed', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Is Complited')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='main.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Stage',
                'verbose_name_plural': 'Stages',
            },
        ),
        migrations.CreateModel(
            name='StageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(blank=True, null=True, upload_to=main.models.stage.upload_image, verbose_name='Url')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.stage', verbose_name='Stage')),
            ],
            options={
                'verbose_name': 'Stage Image',
                'verbose_name_plural': 'Stage Images',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.supervisor', verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
            },
        ),
        migrations.AddField(
            model_name='renovation',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.supervisor', verbose_name='Supervisor'),
        ),
    ]
