# Generated by Django 5.1.2 on 2025-01-20 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_supervisor_session_supervisor'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renovation',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.customer', verbose_name='Customer'),
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
    ]
