# Generated by Django 5.1.2 on 2025-01-20 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_session_customer_alter_session_supervisor'),
        ('main', '0002_alter_renovation_supervisor_delete_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renovation',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.customer', verbose_name='Customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='renovation',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.supervisor', verbose_name='Supervisor'),
        ),
    ]
