# Generated by Django 5.1.2 on 2025-01-16 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_worktype_stagetype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StageType',
            new_name='Stage_Type',
        ),
        migrations.RenameModel(
            old_name='WorkType',
            new_name='Work_Type',
        ),
    ]
