# Generated by Django 5.1.2 on 2025-01-16 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0002_remove_stage_work_stage_work'),
        ('main', '0004_delete_stage_type_delete_work_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='default.work')),
            ],
        ),
    ]
