# Generated by Django 5.1.2 on 2025-01-16 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='main.work')),
            ],
        ),
    ]
