# Generated by Django 5.1.2 on 2025-01-16 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='renovation',
            name='work',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.work'),
            preserve_default=False,
        ),
    ]
