# Generated by Django 5.1.2 on 2025-01-16 21:00

import main.models.renovation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_renovation_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renovation',
            name='track',
            field=models.CharField(default=main.models.renovation.generate_random_string, editable=False, max_length=16),
        ),
    ]
