# Generated by Django 5.1.2 on 2025-01-16 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_work_renovation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='renovation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='main.renovation', unique=True),
        ),
    ]
