# Generated by Django 5.1.2 on 2025-01-16 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0002_remove_stage_work_stage_work'),
        ('main', '0019_alter_work_renovation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='work_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='works', to='default.work'),
        ),
    ]
