# Generated by Django 5.1.2 on 2025-01-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_work_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='is_completed',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
