# Generated by Django 5.1.2 on 2025-01-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_stage_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='name_ka',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
