# Generated by Django 5.1.2 on 2025-01-17 01:19

import django.db.models.deletion
import main.models.renovation
import main.models.stage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0006_alter_stage_options_alter_work_options_and_more'),
        ('main', '0022_stage_name_en_stage_name_ka_stage_name_ru'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='renovation',
            options={'verbose_name': 'Renovation', 'verbose_name_plural': 'Renovations'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'verbose_name': 'Stage', 'verbose_name_plural': 'Stages'},
        ),
        migrations.AlterModelOptions(
            name='supervisor',
            options={'verbose_name': 'Supervisor', 'verbose_name_plural': 'Supervisors'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Work', 'verbose_name_plural': 'Works'},
        ),
        migrations.AlterField(
            model_name='renovation',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='renovation',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='renovation',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='renovation',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.supervisor', verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='renovation',
            name='track',
            field=models.CharField(default=main.models.renovation.generate_random_string, editable=False, max_length=16, verbose_name='Track'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='is_completed',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Is Complited'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='name_ka',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='main.work', verbose_name='Work'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='firstname',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Login'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='lastname',
            field=models.CharField(max_length=255, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='work',
            name='renovation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='main.renovation', unique=True, verbose_name='Renovation'),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='works', to='default.work', verbose_name='Work'),
        ),
        migrations.CreateModel(
            name='StageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(blank=True, null=True, upload_to=main.models.stage.upload_image)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.stage')),
            ],
        ),
    ]
