# Generated by Django 5.1.2 on 2025-01-17 01:25

import main.models.stage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_renovation_options_alter_session_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stageimage',
            options={'verbose_name': 'Stage Image', 'verbose_name_plural': 'Stage Images'},
        ),
        migrations.RenameField(
            model_name='stageimage',
            old_name='description',
            new_name='stage',
        ),
        migrations.AlterField(
            model_name='stageimage',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.stage.upload_image, verbose_name='Url'),
        ),
    ]
