# Generated by Django 5.1.2 on 2025-01-18 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0007_rename_work_service_alter_service_options_and_more'),
        ('main', '0025_alter_session_supervisor_alter_stageimage_stage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='work_type',
        ),
        migrations.AddField(
            model_name='work',
            name='service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='default.service', verbose_name='Service'),
        ),
    ]
