# Generated by Django 5.1.2 on 2025-01-20 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_supervisor_session_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.customer', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='session',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.supervisor', verbose_name='Supervisor'),
        ),
    ]
