# Generated by Django 5.1.2 on 2025-01-21 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customer_email_verified_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email_verified_at',
            new_name='email_verified',
        ),
    ]
