# Generated by Django 5.1.2 on 2025-02-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_email_verified_at_customer_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
