# Generated by Django 5.1.2 on 2025-01-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='work',
        ),
        migrations.AddField(
            model_name='stage',
            name='work',
            field=models.ManyToManyField(related_name='stages', to='default.work'),
        ),
    ]
