# Generated by Django 5.1.2 on 2025-01-20 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0002_user_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
