# Generated by Django 5.1.2 on 2025-01-16 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0003_stage_name_en_stage_name_ka_stage_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='work',
            name='name_en',
        ),
    ]
