# Generated by Django 5.1.2 on 2025-01-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0004_remove_stage_name_en_remove_work_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='work',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Name'),
        ),
    ]
