# Generated by Django 5.1.2 on 2025-01-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0005_stage_name_en_work_name_en'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'verbose_name': 'Stage', 'verbose_name_plural': 'Stages'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Work', 'verbose_name_plural': 'Works'},
        ),
        migrations.AlterField(
            model_name='stage',
            name='work',
            field=models.ManyToManyField(related_name='stages', to='default.work', verbose_name='Work'),
        ),
    ]
