# Generated by Django 5.1.2 on 2025-01-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0006_alter_stage_options_alter_work_options_and_more'),
        ('main', '0025_alter_session_supervisor_alter_stageimage_stage_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Work',
            new_name='Service',
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.RemoveField(
            model_name='stage',
            name='work',
        ),
        migrations.AddField(
            model_name='stage',
            name='service',
            field=models.ManyToManyField(related_name='stages', to='default.service', verbose_name='Service'),
        ),
    ]
